### ISSUE TITLE
Logo proposal snoopm

### ISSUE THREAD

**Issue by psikoz** [carvilsi/snoopm#1]
Hey @carvilsi 

I want to design a logo for snoopm. Please let me know what you think.

**Comment by carvilsi** [comment]
Hello @psikoz 
You are so welcome and free to design a logo for snoopm. 😄

**Comment by psikoz** [comment]
I designed a logo that remind of npm. I hope you like it.

![snoopm](https://user-images.githubusercontent.com/40601249/42127974-97d943d0-7caa-11e8-9d80-26c2b050a81b.jpg)

**Comment by carvilsi** [comment]
Thanks a lot @psikoz 
I love it ❤️ 
Do you want to make a PR or should I just put it there? I would like more your PR because is a way that your collaboration would be present in the sNooPM repo ;)

**Comment by psikoz** [comment]
I hope you like it! :) I sent a pull-request.

**Comment by carvilsi** [comment]
Thanks! I like it so much (you got the whole idea) 👍 
Im going to close this and merge your PR.
